"""init

Revision ID: 50133dab61df
 Revises:
Create Date: 2024-08-03 18:57:05.719708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '50133dab61df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bets',
                    sa.Column(
                        'event_id', sa.String(),
                        nullable=False
                    ),
                    sa.Column(
                        'sum_bet',
                        sa.DECIMAL(precision=10, scale=2),
                        nullable=False
                    ),
                    sa.Column(
                        'status',
                        sa.String(),
                        nullable=False
                    ),
                    sa.PrimaryKeyConstraint('event_id')
                    )
    op.create_index(
        op.f('ix_Bets_event_id'),
        'Bets', ['event_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Bets_event_id'), table_name='Bets')
    op.drop_table('Bets')
    # ### end Alembic commands ###
