version: '3'
services:
  db-test:
    image: postgres:16.2-alpine
    restart: always
    hostname: bet-maker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bet-maker
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - bet-maker:/var/lib/postgresql/data
    ports:
      - '5432:5432'



volumes:
  bet-maker:
    driver: local