name: CI for service Bet-Maker

on:
  push:
    branches:
      - '**'
      - main

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry add --dev flake8
    - name: Test with flake8 line-provider
      run: |
        poetry run flake8 line-provider/
    - name: Test with flake8 bet-maker
      run: |
        poetry run flake8 bet-maker/

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Up Testing stand
      run: |
        docker-compose up -d --build
    - name: Tests line-provider
      run: |
        poetry run pytest line-provider/tests
    - name: Tests bet-maker
      run: |
        poetry run pytest bet-maker/tests
    - name: Down test-stand
      run: |
        docker-compose down
